<?php

namespace MiCocinaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedidaRepository extends EntityRepository
{
}
