mi_cocina:
    resource: "@MiCocinaBundle/Controller/"
    type:     annotation
    prefix:   /backend

users:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
